definitions:
  dentists.Dentist:
    properties:
      first_name:
        type: string
      idDentist:
        type: integer
      last_name:
        type: string
      registration_number:
        type: integer
    type: object
info:
  contact:
    name: API Support
    url: https://developers.gogogo.ctd.com.ar/support
  description: This API Handle Clinica.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.gogogo.ctd.com.ar/es_ar/terminos-y-condiciones
  title: Clinica Odotntologica Dientes GoGoGo
  version: "1.0"
paths:
  /dentists/{id}:
    get:
      description: Gets a dentist by ID from the repository
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dentists.Dentist'
      summary: Gets a dentist by ID
      tags:
      - dentists.Dentist
swagger: "2.0"
