definitions:
  dentists.Dentist:
    properties:
      first_name:
        type: string
      idDentist:
        type: integer
      last_name:
        type: string
      registration_number:
        type: integer
    type: object
  patients.Patient:
    properties:
      address:
        type: string
      credential_id:
        type: string
      discharge_date:
        type: string
      first_name:
        type: string
      idPatient:
        type: integer
      last_name:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.gogogo.ctd.com.ar/support
  description: This API Handle Clinica.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.gogogo.ctd.com.ar/es_ar/terminos-y-condiciones
  title: Clinica Odotntologica Dientes GoGoGo
  version: "1.0"
paths:
  /dentists/{id}:
    get:
      description: Gets a dentist by ID from the repository
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dentists.Dentist'
      summary: Gets a dentist by ID
      tags:
      - dentists.Dentist
  /patients:
    patch:
      description: Modifica uno o más atributos de un paciente existente y almacena
        los cambios en la base de datos
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/patients.Patient'
      summary: Modifica uno o más atributos de un paciente existente
      tags:
      - patients
    post:
      description: Guarda nuevo paciente en la base de datos
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/patients.Patient'
      summary: Guarda nuevo paciente
      tags:
      - patients
    put:
      description: Modifica un paciente existente por id y lo almacena en la base
        de datos
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/patients.Patient'
      summary: Modifica un paciente existente
      tags:
      - patients
  /patients/{id}:
    delete:
      description: Elimina un paciente por id en la base de datos
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: Paciente
      summary: Elimina un paciente por id
      tags:
      - patients
    get:
      description: Obtiene un paciente por id desde la base de datos
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/patients.Patient'
      summary: Obtiene un paciente por id
      tags:
      - patients
swagger: "2.0"
