version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: 'mysql-db'
    environment:
      MYSQL_DATABASE: 'finalGogogo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# Names our volume
volumes:
  my-db: